import type { RailItem, StorySceneContent } from "@/lib/story-types";

export const PRODUCT_STORY_SCENES: StorySceneContent[] = [
  {
    id: "surface",
    eyebrow: "Product",
    title: "随身携带的 AI 感知系统。",
    summary: "圆盘盒、无线耳机、胸前相机——三件组合，覆盖视觉采集、语音交互和触觉反馈。",
    details: [
      { label: "圆盘盒", body: "触控面板 + 耳机充电仓 + 状态指示灯，一体成型。" },
      { label: "胸前相机", body: "8g 磁吸模块，安静待机，按下即拍。" },
      { label: "无线耳机", body: "AI 结果通过语音实时传达，解放双手和视线。" },
    ],
    stageLabel: "产品总览",
    stageSummary: "三件套，各司其职。",
    stageTags: ["圆盘盒", "相机", "耳机"],
    assetSlots: ["产品主镜头", "材质近景", "状态切换短片"],
    tone: "pearl",
    viewerPatch: {
      isOpen: false,
      camDetached: false,
      earbudsOut: false,
      mode: "offline",
      colorway: "pearl",
      caseMode: "office_mode",
      xrayOn: false,
      nightOn: false,
      pivotInspectActive: false,
    },
  },
  {
    id: "geometry",
    eyebrow: "Structure",
    title: "打开盒子，取出装备。",
    summary: "112° 磁吸转轴单手开合，耳机自动弹出就位，相机磁吸分离即可佩戴。",
    details: [
      { label: "转轴开合", body: "精密阻尼铰链，开合手感确定，角度可停。" },
      { label: "耳机弹出", body: "盒盖打开后耳机微抬，方便单手取用。" },
      { label: "相机分离", body: "磁吸卡扣释放，挂上胸前即进入待机。" },
    ],
    stageLabel: "结构细节",
    stageSummary: "每一步都有触觉确认。",
    stageTags: ["转轴", "弹出", "磁吸"],
    assetSlots: ["转轴微距", "开盖动作", "结构示意"],
    tone: "midnight",
    viewerPatch: {
      isOpen: true,
      pivotAngleDeg: 88,
      pivotState: "opening",
      earbudsOut: true,
      camDetached: false,
      mode: "offline",
      colorway: "pearl",
      caseMode: "commute_mode",
    },
  },
  {
    id: "wear",
    eyebrow: "Daily Use",
    title: "戴上它，开始你的一天。",
    summary: "相机挂在胸前感知环境，耳机传回 AI 反馈。通勤、工作、探索——它跟着你。",
    details: [
      { label: "佩戴", body: "相机 8g，耳机 4.5g，几乎无感。" },
      { label: "触发", body: "按下盒面按键或轻触耳机，开始环境感知。" },
      { label: "反馈", body: "识别结果 2-5 秒内通过耳机语音播报。" },
    ],
    stageLabel: "日常佩戴",
    stageSummary: "轻到忘记它的存在。",
    stageTags: ["佩戴", "触发", "反馈"],
    assetSlots: ["佩戴场景", "触发动作", "结果联动画面"],
    tone: "glacier",
    viewerPatch: {
      isOpen: true,
      camDetached: true,
      earbudsOut: true,
      mode: "hybrid",
      colorway: "glacier",
      caseMode: "commute_mode",
      dreamOn: true,
    },
  },
  {
    id: "engineering",
    eyebrow: "Engineering",
    title: "可检视，可拆解，可量产。",
    summary: "透视结构、材质标注、公差检查——从设计到制造的完整工程视角。",
    details: [
      { label: "爆炸视图", body: "所有零件分层展示，装配关系一目了然。" },
      { label: "材质标注", body: "每个部件标注材料、工艺和表面处理。" },
      { label: "制造就绪", body: "可直接导出工程文件，进入开模流程。" },
    ],
    stageLabel: "工程视角",
    stageSummary: "从渲染到量产。",
    stageTags: ["爆炸图", "材质", "制造"],
    assetSlots: ["爆炸视图", "材质说明", "制造状态录屏"],
    tone: "obsidian",
    viewerPatch: {
      isOpen: true,
      camDetached: true,
      earbudsOut: true,
      mode: "online",
      colorway: "graphite",
      caseMode: "office_mode",
      xrayOn: true,
      pivotInspectActive: true,
      pivotExplodeActive: true,
      nightOn: true,
    },
  },
];

export const WORKFLOW_STORY_SCENES: StorySceneContent[] = [
  {
    id: "demo",
    eyebrow: "Step 1",
    title: "先试用，再决定。",
    summary: "打开 Demo 页面，上传一张照片或使用摄像头，立即看到 AI 的环境理解能力。",
    details: [
      { label: "即开即用", body: "无需注册，浏览器中直接体验。" },
      { label: "实时推理", body: "上传图片后数秒内返回分析结果。" },
      { label: "多种任务", body: "支持视觉问答 (VQA) 和文字识别 (OCR)。" },
    ],
    stageLabel: "在线体验",
    stageSummary: "零门槛，浏览器即可开始。",
    stageTags: ["Demo", "VQA", "OCR"],
    assetSlots: ["主体验录屏", "输入动作", "结果返回"],
    tone: "pearl",
  },
  {
    id: "dataset",
    eyebrow: "Step 2",
    title: "上传你的数据。",
    summary: "把你场景中的真实样本上传到平台，创建数据集版本，为训练做好准备。",
    details: [
      { label: "批量上传", body: "拖拽文件夹，自动解析标注格式。" },
      { label: "版本管理", body: "每次冻结生成不可变快照，训练可复现。" },
      { label: "在线浏览", body: "逐条查看样本和标注，直接修正错误。" },
    ],
    stageLabel: "数据管理",
    stageSummary: "上传、整理、冻结版本。",
    stageTags: ["上传", "版本", "浏览"],
    assetSlots: ["上传录屏", "版本冻结", "数据浏览"],
    tone: "midnight",
  },
  {
    id: "train",
    eyebrow: "Step 3",
    title: "一键启动训练。",
    summary: "选择数据集版本和基础模型，提交训练任务。实时查看日志、损失曲线和评测指标。",
    details: [
      { label: "任务面板", body: "训练进度、GPU 占用、预计完成时间一目了然。" },
      { label: "自动评测", body: "训练结束自动运行评测集，对比历史版本。" },
      { label: "产物管理", body: "模型权重、配置文件统一归档。" },
    ],
    stageLabel: "模型训练",
    stageSummary: "训练、评测、对比，一站完成。",
    stageTags: ["训练", "评测", "对比"],
    assetSlots: ["训练状态", "评测对比", "日志与指标"],
    tone: "glacier",
  },
  {
    id: "release",
    eyebrow: "Step 4",
    title: "发布上线，随时回滚。",
    summary: "将训练好的模型注册到模型仓，通过 alias 切换线上版本。不满意？一键回退。",
    details: [
      { label: "模型仓", body: "所有版本集中管理，历史可追溯。" },
      { label: "Alias 切换", body: "production / staging 指针随时切换。" },
      { label: "操作审计", body: "谁在什么时间做了什么，全部有记录。" },
    ],
    stageLabel: "发布管理",
    stageSummary: "发布即版本控制。",
    stageTags: ["Models", "Alias", "Rollback"],
    assetSlots: ["版本切换", "发布动作", "审计记录"],
    tone: "obsidian",
  },
];

export const PRICING_STORY_SCENES: StorySceneContent[] = [
  {
    id: "entry",
    eyebrow: "Pricing",
    title: "从免费体验开始。",
    summary: "先用 Demo 感受产品能力，准备好了再进入完整工作流。按你的节奏来。",
    details: [
      { label: "免费体验", body: "Demo 页面对所有人开放，无需付费。" },
      { label: "按需升级", body: "需要训练和部署时再开通 Studio。" },
      { label: "团队扩展", body: "多人协作和更高配额另行开通。" },
    ],
    stageLabel: "选择方案",
    stageSummary: "按你的阶段选择。",
    stageTags: ["免费", "付费", "团队"],
    assetSlots: ["进入路径图", "体验入口", "候补说明"],
    tone: "pearl",
  },
  {
    id: "explore",
    eyebrow: "Explore",
    title: "Explore — 免费体验。",
    summary: "访问公开 Demo，体验 AI 视觉问答和文字识别。零成本了解产品能力。",
    details: [
      { label: "公开 Demo", body: "上传图片即可体验，无需账号。" },
      { label: "基础推理", body: "使用公共模型，感受核心能力。" },
      { label: "无限制", body: "不限次数，随时回来再试。" },
    ],
    stageLabel: "Explore",
    stageSummary: "免费，无门槛。",
    stageTags: ["Demo", "免费", "即开即用"],
    assetSlots: ["公开 Demo 录屏", "基础结果", "体验说明"],
    tone: "midnight",
  },
  {
    id: "studio",
    eyebrow: "Studio",
    title: "Studio — 完整工作流。",
    summary: "创建项目、管理数据集、训练模型、发布上线。从实验到生产的完整链路。",
    details: [
      { label: "项目管理", body: "多项目隔离，数据和模型分别管理。" },
      { label: "训练 & 部署", body: "提交训练、评测、发布，全在一个平台。" },
      { label: "审计日志", body: "所有操作自动记录，满足合规需求。" },
    ],
    stageLabel: "Studio",
    stageSummary: "从数据到部署，一站完成。",
    stageTags: ["项目", "训练", "部署"],
    assetSlots: ["控制台总览", "训练与发布", "审计默认值"],
    tone: "glacier",
  },
  {
    id: "team",
    eyebrow: "Team",
    title: "Team — 团队协作。",
    summary: "多人共享 workspace，更高并发和存储配额，细粒度权限控制。",
    details: [
      { label: "共享空间", body: "团队成员在同一 workspace 协作。" },
      { label: "弹性配额", body: "按团队规模调整计算和存储资源。" },
      { label: "权限管理", body: "按角色分配数据、模型和发布权限。" },
    ],
    stageLabel: "Team",
    stageSummary: "为团队规模化设计。",
    stageTags: ["Workspace", "配额", "权限"],
    assetSlots: ["团队协作界面", "额度说明", "权限示意"],
    tone: "obsidian",
  },
];

export const DOCS_STORY_SCENES: StorySceneContent[] = [
  {
    id: "quickstart",
    eyebrow: "Docs",
    title: "5 分钟快速开始。",
    summary: "从打开 Demo 到完成第一次推理，跟着指引走一遍核心流程。",
    details: [
      { label: "产品概览", body: "了解硬件组成和三种工作模式。" },
      { label: "Demo 上手", body: "上传图片，发起推理，查看结果。" },
      { label: "进入控制台", body: "注册后开始管理数据和训练模型。" },
    ],
    stageLabel: "快速开始",
    stageSummary: "从这里出发。",
    stageTags: ["概览", "Demo", "控制台"],
    assetSlots: ["阅读地图", "控制台路径", "安全说明"],
    tone: "pearl",
  },
  {
    id: "product-docs",
    eyebrow: "Product Guide",
    title: "产品使用指南。",
    summary: "硬件操作、模式切换、佩戴方式、固件更新——完整的产品使用手册。",
    details: [
      { label: "硬件操作", body: "开合、佩戴、充电、状态灯含义。" },
      { label: "模式切换", body: "离线/混合/在线模式的触发条件和行为差异。" },
      { label: "固件更新", body: "OTA 更新流程和版本管理。" },
    ],
    stageLabel: "产品文档",
    stageSummary: "硬件 + 固件。",
    stageTags: ["硬件", "模式", "固件"],
    assetSlots: ["产品说明图", "模式切换", "体验入口"],
    tone: "midnight",
  },
  {
    id: "workflow-docs",
    eyebrow: "Workflow Guide",
    title: "工作流文档。",
    summary: "数据集管理、模型训练、评测对比、发布回滚——平台操作的完整指南。",
    details: [
      { label: "数据集", body: "上传格式、版本冻结、标注规范。" },
      { label: "训练", body: "任务创建、参数配置、日志解读。" },
      { label: "发布", body: "模型注册、alias 管理、回滚操作。" },
    ],
    stageLabel: "工作流文档",
    stageSummary: "平台操作指南。",
    stageTags: ["数据集", "训练", "发布"],
    assetSlots: ["工作流图", "训练说明", "发布说明"],
    tone: "glacier",
  },
  {
    id: "security-docs",
    eyebrow: "Security",
    title: "安全与合规。",
    summary: "数据加密、访问控制、审计日志、合规认证——平台安全机制的完整说明。",
    details: [
      { label: "签名访问", body: "所有资源通过签名 URL 访问，不暴露原始路径。" },
      { label: "数据加密", body: "传输和存储全程加密，密钥独立管理。" },
      { label: "合规审计", body: "操作日志不可篡改，支持导出和审查。" },
    ],
    stageLabel: "安全文档",
    stageSummary: "安全是默认值。",
    stageTags: ["加密", "访问控制", "审计"],
    assetSlots: ["安全拓扑", "签名路径", "部署说明"],
    tone: "obsidian",
  },
];

export const CONTACT_STORY_SCENES: StorySceneContent[] = [
  {
    id: "mail",
    eyebrow: "Contact",
    title: "和我们聊聊。",
    summary: "产品合作、内测申请、技术问题——发邮件是最直接的方式。",
    details: [
      { label: "产品合作", body: "讨论硬件定制、场景适配和 OEM 合作。" },
      { label: "内测申请", body: "申请设备体验或 Studio 控制台试用。" },
      { label: "安全问题", body: "标题标注 Security，我们会优先处理。" },
    ],
    stageLabel: "hello@qihang.ai",
    stageSummary: "48 小时内回复。",
    stageTags: ["hello@qihang.ai", "合作", "内测"],
    assetSlots: ["hello@qihang.ai", "48 小时内回复", "英国工作时间"],
    tone: "pearl",
  },
  {
    id: "topics",
    eyebrow: "Topics",
    title: "这些话题我们很乐意聊。",
    summary: "不管你是产品经理、工程师还是研究人员，我们都期待听到你的想法。",
    details: [
      { label: "使用场景", body: "你打算在什么环境下使用环境 AI？" },
      { label: "技术对接", body: "API 集成、模型定制、私有部署需求。" },
      { label: "反馈建议", body: "产品体验中遇到的任何问题和改进建议。" },
    ],
    stageLabel: "聊什么都行",
    stageSummary: "我们在听。",
    stageTags: ["场景", "技术", "反馈"],
    assetSlots: ["原型照片", "工作流录屏", "合作说明"],
    tone: "midnight",
  },
  {
    id: "security",
    eyebrow: "Security",
    title: "安全问题，快速通道。",
    summary: "发现安全漏洞或隐私问题？在邮件标题标注 Security，我们会在 24 小时内响应。",
    details: [
      { label: "漏洞报告", body: "标题标注 Security，附上复现步骤。" },
      { label: "隐私问题", body: "数据删除、访问权限相关问题优先处理。" },
      { label: "合规咨询", body: "GDPR、数据主权等合规需求欢迎咨询。" },
    ],
    stageLabel: "安全通道",
    stageSummary: "24 小时内响应。",
    stageTags: ["Security", "Privacy", "Compliance"],
    assetSlots: ["隐私边界图", "安全说明", "响应流程"],
    tone: "obsidian",
  },
];

export const UPDATES_STORY_SCENES: StorySceneContent[] = [
  {
    id: "march-product",
    eyebrow: "2026.03",
    title: "产品页全面升级",
    summary: "首页和产品页重新设计，以产品实物为核心展开叙事，取代之前的功能卡片堆叠。",
    details: [
      { label: "新首页", body: "3D 产品舞台 + 滚动驱动交互。" },
      { label: "新产品页", body: "从外观到结构到工程视角，连续呈现。" },
      { label: "文案优化", body: "面向用户价值重写全站文案。" },
    ],
    stageLabel: "v0.2 发布",
    stageSummary: "全新视觉体验。",
    stageTags: ["首页", "产品页", "文案"],
    assetSlots: ["新版首页录屏", "产品页录屏", "旧新版对比"],
    tone: "pearl",
  },
  {
    id: "march-demo",
    eyebrow: "2026.03",
    title: "Demo 体验优化",
    summary: "3D 产品查看器前置，推理结果更直观，高级控制项折叠进抽屉面板。",
    details: [
      { label: "产品查看器", body: "首屏即可交互查看 3D 产品模型。" },
      { label: "结果展示", body: "推理结果以卡片形式清晰呈现。" },
      { label: "控制面板", body: "耳机配色、X 光等高级功能收入侧边栏。" },
    ],
    stageLabel: "Demo 优化",
    stageSummary: "体验优先，控制收敛。",
    stageTags: ["Demo", "3D", "推理"],
    assetSlots: ["Demo 主舞台", "结果摘要", "控制抽屉"],
    tone: "midnight",
  },
  {
    id: "march-security",
    eyebrow: "2026.03",
    title: "安全基线加固",
    summary: "CSRF 防护、请求限流、签名 URL 访问——生产环境安全默认值全面收紧。",
    details: [
      { label: "CSRF", body: "所有状态变更请求强制 CSRF token 校验。" },
      { label: "限流", body: "API 端点按用户和 IP 双维度限流。" },
      { label: "签名访问", body: "存储对象统一通过带时效的签名 URL 访问。" },
    ],
    stageLabel: "安全更新",
    stageSummary: "安全是默认值，不是选项。",
    stageTags: ["CSRF", "限流", "签名"],
    assetSlots: ["安全拓扑", "配置校验", "访问路径"],
    tone: "obsidian",
  },
];

export const WORKFLOW_RAIL: RailItem[] = [
  { label: "01", title: "体验", body: "打开 Demo，感受环境 AI 能力。", meta: "Demo" },
  { label: "02", title: "数据", body: "上传样本，创建数据集版本。", meta: "Datasets" },
  { label: "03", title: "训练", body: "提交训练任务，查看评测结果。", meta: "Train" },
  { label: "04", title: "发布", body: "注册模型，切换线上版本。", meta: "Release" },
];

export const PRICING_COMPARE_RAIL: RailItem[] = [
  { label: "Explore", title: "免费体验", body: "公开 Demo、基础推理、无需注册。", meta: "Free" },
  { label: "Studio", title: "完整工作流", body: "项目、数据集、训练、模型仓、发布。", meta: "Waitlist" },
  { label: "Team", title: "团队协作", body: "多人 workspace、弹性配额、权限管理。", meta: "Soon" },
];

export const DOCS_PATH_RAIL: RailItem[] = [
  { label: "Start", title: "快速开始", body: "5 分钟跑通核心流程。" },
  { label: "Product", title: "产品指南", body: "硬件操作和模式切换。" },
  { label: "Workflow", title: "工作流", body: "数据、训练、发布。" },
  { label: "Security", title: "安全", body: "加密、访问控制、审计。" },
];

export const UPDATE_TIMELINE_RAIL: RailItem[] = [
  { label: "2026.03", title: "产品页升级", body: "全新视觉设计和交互体验。" },
  { label: "2026.03", title: "Demo 优化", body: "产品查看器前置，推理体验优化。" },
  { label: "2026.03", title: "安全加固", body: "CSRF、限流、签名访问全面上线。" },
];
