import type { RailItem, StorySceneContent } from "@/lib/story-types";

export const PRODUCT_STORY_SCENES: StorySceneContent[] = [
  {
    id: "surface",
    eyebrow: "Product Surface",
    title: "先把硬件摆上舞台，再讲它能做什么。",
    summary: "产品页先让人看到一个真实对象，而不是先被参数、术语和功能块包围。",
    details: [
      { label: "圆盘盒", body: "把耳机、反馈与触控收在一块稳定的随身表面里。" },
      { label: "胸前相机", body: "默认安静待机，只在明确动作之后进入采集链路。" },
      { label: "离线优先", body: "先给出本地反馈，再决定是否继续接入增强能力。" },
    ],
    stageLabel: "产品先出现",
    stageSummary: "这页的主角不是说明卡，而是同一个会被打开、佩戴和检视的产品舞台。",
    stageTags: ["圆盘盒", "胸前相机", "离线链路"],
    assetSlots: ["产品主镜头", "材质近景", "状态切换短片"],
    tone: "pearl",
    viewerPatch: {
      isOpen: false,
      camDetached: false,
      earbudsOut: false,
      mode: "offline",
      colorway: "pearl",
      caseMode: "office_mode",
      xrayOn: false,
      nightOn: false,
      pivotInspectActive: false,
    },
  },
  {
    id: "geometry",
    eyebrow: "Geometry",
    title: "开合关系和结构秩序，应该像镜头一样被理解。",
    summary: "转轴、耳机入仓和盒体关系不再写成说明文，而是作为产品几何的一部分被感知。",
    details: [
      { label: "转轴开合", body: "通过舞台变化把开合状态讲清，而不是交给技术文档兜底。" },
      { label: "耳机入仓", body: "出仓与回收要自然、可信，并且一眼可读。" },
      { label: "结构层次", body: "让外形、连接和内部秩序在同一镜头下被看到。" },
    ],
    stageLabel: "几何关系展开",
    stageSummary: "随着视线推进，盒体打开、耳机抬起，结构关系逐步显露。",
    stageTags: ["开合", "入仓", "结构"],
    assetSlots: ["转轴微距", "开盖动作", "结构示意"],
    tone: "midnight",
    viewerPatch: {
      isOpen: true,
      pivotAngleDeg: 88,
      pivotState: "opening",
      earbudsOut: true,
      camDetached: false,
      mode: "offline",
      colorway: "pearl",
      caseMode: "commute_mode",
    },
  },
  {
    id: "wear",
    eyebrow: "Wear & Trigger",
    title: "佩戴、触发、退出，都要像日常动作而不是系统命令。",
    summary: "用户不是在操作一堆开关，而是在一个持续存在的产品表面里自然进入 AI 能力。",
    details: [
      { label: "佩戴场景", body: "产品进入身体周边时，状态变化应该即时且克制。" },
      { label: "显式触发", body: "启动不是隐藏行为，用户应清楚知道何时开始采集。" },
      { label: "结果反馈", body: "从图像到结果的回路需要始终留在同一条体验线上。" },
    ],
    stageLabel: "佩戴与触发",
    stageSummary: "相机离开停泊状态，产品从静止展示进入可被调用的真实场景。",
    stageTags: ["佩戴", "触发", "反馈"],
    assetSlots: ["佩戴场景", "触发动作", "结果联动画面"],
    tone: "glacier",
    viewerPatch: {
      isOpen: true,
      camDetached: true,
      earbudsOut: true,
      mode: "hybrid",
      colorway: "glacier",
      caseMode: "commute_mode",
      dreamOn: true,
    },
  },
  {
    id: "engineering",
    eyebrow: "Engineering View",
    title: "工程预览留在后段，但仍然属于同一个舞台。",
    summary: "制造、转轴检视和结构分解不抢首屏注意力，却必须在后段给出可信的工程感。",
    details: [
      { label: "结构检视", body: "需要时打开检视状态，让工程关系直接暴露出来。" },
      { label: "制造信息", body: "把材质、间隙和版本信息留在后段，避免首屏噪音。" },
      { label: "导出准备", body: "工程团队看到的不只是美观，而是可继续推进的对象。" },
    ],
    stageLabel: "工程与制造预览",
    stageSummary: "末段转入更技术的观察视角，但仍保持与产品舞台一致的气质。",
    stageTags: ["检视", "制造", "导出"],
    assetSlots: ["爆炸视图", "材质说明", "制造状态录屏"],
    tone: "obsidian",
    viewerPatch: {
      isOpen: true,
      camDetached: true,
      earbudsOut: true,
      mode: "online",
      colorway: "graphite",
      caseMode: "office_mode",
      xrayOn: true,
      pivotInspectActive: true,
      pivotExplodeActive: true,
      nightOn: true,
    },
  },
];

export const WORKFLOW_STORY_SCENES: StorySceneContent[] = [
  {
    id: "demo",
    eyebrow: "How It Works",
    title: "先体验，再进入系统，而不是先读完流程图。",
    summary: "工作流页要把复杂步骤压成一条连续路径，让用户知道自己会怎么走，而不是一上来就面对系统结构图。",
    details: [
      { label: "先体验", body: "先在主舞台里理解设备、输入和反馈。" },
      { label: "再进入控制台", body: "确认产品形态之后，再进入数据和训练工作。" },
      { label: "保持一条线", body: "体验、整理、训练和发布不应该像四个独立网页。" },
    ],
    stageLabel: "先从 Demo 开始",
    stageSummary: "用户先看到自己会从哪里进入，而不是先被一堆系统名词包围。",
    stageTags: ["Demo", "体验", "入口"],
    assetSlots: ["主体验录屏", "输入动作", "结果返回"],
    tone: "pearl",
  },
  {
    id: "dataset",
    eyebrow: "Dataset Flow",
    title: "数据整理不是后台杂务，而是产品体验的延伸。",
    summary: "上传、整理和冻结版本应该顺着同一条轨道出现，而不是被切成零散工具页。",
    details: [
      { label: "上传", body: "样本进入系统后，立刻进入可继续整理的受管路径。" },
      { label: "冻结", body: "数据版本的边界要明确，方便训练与评测复用。" },
      { label: "可回放", body: "后续训练和发布都能回溯到具体数据上下文。" },
    ],
    stageLabel: "整理与冻结",
    stageSummary: "中段开始进入工作流深水区，但仍保持清楚的路径感。",
    stageTags: ["上传", "冻结", "回放"],
    assetSlots: ["上传录屏", "版本冻结", "数据浏览"],
    tone: "midnight",
  },
  {
    id: "train",
    eyebrow: "Training Loop",
    title: "训练和评测属于同一个决策回路。",
    summary: "训练不是孤立作业，参数、日志、指标和结果必须与后续评测保持连续关系。",
    details: [
      { label: "训练任务", body: "创建任务之后，应该能连续看到日志、指标和产物。" },
      { label: "评测回放", body: "对比不是事后补充，而是发布前的决定依据。" },
      { label: "结构一致", body: "训练和评测应该共享同样的版本边界与上下文。" },
    ],
    stageLabel: "训练与评测",
    stageSummary: "工作流的中后段转向更高信息密度，但不改变叙事主线。",
    stageTags: ["训练", "日志", "评测"],
    assetSlots: ["训练状态", "评测对比", "日志与指标"],
    tone: "glacier",
  },
  {
    id: "release",
    eyebrow: "Release",
    title: "发布不是终点，而是带着回退能力的显式动作。",
    summary: "模型仓、alias 和回滚路径需要在最后一段一起出现，形成完整的发布闭环。",
    details: [
      { label: "模型仓", body: "产物进入统一仓库，后续状态变更才有可信边界。" },
      { label: "Alias", body: "发布和回滚共用同一条线，不拆成不同概念入口。" },
      { label: "审计", body: "最终动作必须可追踪、可复盘。" },
    ],
    stageLabel: "发布与回滚",
    stageSummary: "最后一段收束到版本控制、发布指针和审计闭环。",
    stageTags: ["Models", "Alias", "Rollback"],
    assetSlots: ["版本切换", "发布动作", "审计记录"],
    tone: "obsidian",
  },
];

export const PRICING_STORY_SCENES: StorySceneContent[] = [
  {
    id: "entry",
    eyebrow: "Pricing",
    title: "先知道该从哪里进入，而不是先读一页价格表。",
    summary: "这页首先回答的是路径问题：用户应该先体验、先候补，还是直接进入完整工作流。",
    details: [
      { label: "先体验", body: "对大多数人来说，公开 Demo 仍然是最合理的起点。" },
      { label: "再进入工作流", body: "理解产品后，再决定是否进入数据和模型链路。" },
      { label: "按阶段开放", body: "套餐不是炫耀复杂度，而是说明当前的进入方式。" },
    ],
    stageLabel: "从哪里开始",
    stageSummary: "首屏不把用户塞进三张套餐卡，而是先告诉他该走哪条路径。",
    stageTags: ["路径", "体验", "候补"],
    assetSlots: ["进入路径图", "体验入口", "候补说明"],
    tone: "pearl",
  },
  {
    id: "explore",
    eyebrow: "Explore",
    title: "Explore 负责理解产品，不负责一次性打开全部系统。",
    summary: "公开体验层先让用户感知产品形态和基本反馈，不急着暴露高密度控制台能力。",
    details: [
      { label: "公开 Demo", body: "先理解设备、输入和结果链路。" },
      { label: "基础推理", body: "先证明体验闭环，再决定是否继续深入。" },
      { label: "轻量进入", body: "避免在最早阶段就引入复杂协作与额度概念。" },
    ],
    stageLabel: "Explore 路径",
    stageSummary: "这段重点是解释公开体验层为什么存在，以及它的边界是什么。",
    stageTags: ["Demo", "基础推理", "轻量进入"],
    assetSlots: ["公开 Demo 录屏", "基础结果", "体验说明"],
    tone: "midnight",
  },
  {
    id: "studio",
    eyebrow: "Studio",
    title: "Studio 才是完整工作流的入口。",
    summary: "当用户准备好进入数据、训练和模型仓时，Studio 才打开完整表面和版本链路。",
    details: [
      { label: "项目与数据", body: "在同一工作台里整理项目、数据集与版本。" },
      { label: "训练与发布", body: "训练、评测、发布和回滚在一条线上完成。" },
      { label: "审计默认值", body: "对可追溯与安全边界保持明确默认值。" },
    ],
    stageLabel: "Studio 工作流",
    stageSummary: "完整工作流页不抢首屏，但会在中段明确说明它提供的连续能力。",
    stageTags: ["Projects", "Train", "Models"],
    assetSlots: ["控制台总览", "训练与发布", "审计默认值"],
    tone: "glacier",
  },
  {
    id: "team",
    eyebrow: "Team",
    title: "Team 解释的是协作和额度，而不是另一个完全不同的产品。",
    summary: "团队层应该被理解为对现有工作流的扩展，而不是新的一张营销海报。",
    details: [
      { label: "多人 workspace", body: "让协作保持在统一边界里，而不是到处复制版本。" },
      { label: "更高额度", body: "并发、存储和计算能力应随团队规模继续增长。" },
      { label: "权限边界", body: "后续通过更细粒度权限补足多人使用的真实需求。" },
    ],
    stageLabel: "Team 扩展层",
    stageSummary: "最后一段说明规模化协作，而不是再额外造一张产品卡。",
    stageTags: ["Workspace", "Quota", "Permissions"],
    assetSlots: ["团队协作界面", "额度说明", "权限示意"],
    tone: "obsidian",
  },
];

export const DOCS_STORY_SCENES: StorySceneContent[] = [
  {
    id: "map",
    eyebrow: "Docs",
    title: "文档页先给路径，再给细节。",
    summary: "公开站里的文档不是知识库目录，而是帮助用户知道该从哪里开始阅读。",
    details: [
      { label: "产品说明", body: "先理解硬件、模式切换和 Demo 的角色。" },
      { label: "工作流路径", body: "再理解数据、训练、评测和发布如何接续。" },
      { label: "安全默认", body: "最后再读部署、签名访问和安全边界。" },
    ],
    stageLabel: "文档地图",
    stageSummary: "先把阅读顺序讲清，再进入更高信息密度的正式文档。",
    stageTags: ["Product", "Workflow", "Security"],
    assetSlots: ["阅读地图", "控制台路径", "安全说明"],
    tone: "pearl",
  },
  {
    id: "product",
    eyebrow: "Product Reading",
    title: "先读产品形态，避免在术语里迷路。",
    summary: "第一条阅读线先帮助用户理解对象、模式和体验入口，避免把抽象系统名词放在最前面。",
    details: [
      { label: "对象感", body: "用户先知道自己面对的是一个什么产品。" },
      { label: "体验感", body: "再知道 Demo 如何连接到真实使用。" },
      { label: "边界感", body: "最后再接入隐私与状态可见。" },
    ],
    stageLabel: "先读产品",
    stageSummary: "这段把产品说明作为阅读起点，而不是一页目录。",
    stageTags: ["对象", "体验", "边界"],
    assetSlots: ["产品说明图", "模式切换", "体验入口"],
    tone: "midnight",
  },
  {
    id: "workflow",
    eyebrow: "Workflow Reading",
    title: "工作流文档负责把系统结构压平。",
    summary: "当用户已经理解产品之后，工作流文档才展开数据、训练、评测和发布关系。",
    details: [
      { label: "数据", body: "样本如何进入与冻结版本。" },
      { label: "训练", body: "训练任务、日志和指标如何组织。" },
      { label: "发布", body: "模型仓与 alias 如何形成闭环。" },
    ],
    stageLabel: "再读工作流",
    stageSummary: "这段承接产品说明，把系统结构压成一条阅读线。",
    stageTags: ["Datasets", "Train", "Models"],
    assetSlots: ["工作流图", "训练说明", "发布说明"],
    tone: "glacier",
  },
  {
    id: "security",
    eyebrow: "Security Reading",
    title: "安全与部署留在最后，但必须足够清晰。",
    summary: "签名读取、私有存储和安全默认值不必先声夺人，但必须在需要时一眼能找到。",
    details: [
      { label: "签名访问", body: "前端不暴露原始对象路径。" },
      { label: "私有存储", body: "数据与产物保持受管访问。" },
      { label: "安全默认", body: "CSRF、Cookie 与 workspace 共同形成默认边界。" },
    ],
    stageLabel: "最后读安全",
    stageSummary: "最后一段把部署与安全阅读路径收束起来，避免散落在各处。",
    stageTags: ["Signed URLs", "Private Storage", "Defaults"],
    assetSlots: ["安全拓扑", "签名路径", "部署说明"],
    tone: "obsidian",
  },
];

export const CONTACT_STORY_SCENES: StorySceneContent[] = [
  {
    id: "mail",
    eyebrow: "Contact",
    title: "继续聊产品，直接写邮件。",
    summary: "联系方式页不需要堆成表单和卡片，只需要把最直接的沟通入口摆出来。",
    details: [
      { label: "产品合作", body: "讨论硬件形态、设备交互和环境 AI 的真实场景。" },
      { label: "内测候补", body: "预约后续设备体验、控制台试用与反馈渠道。" },
      { label: "隐私与安全", body: "敏感问题可直接标注 Security / Privacy。" },
    ],
    stageLabel: "Primary Channel",
    stageSummary: "当前最直接的沟通方式仍然是邮件，不需要再绕一层繁复表单。",
    stageTags: ["hello@qihang.ai", "产品合作", "Security / Privacy"],
    assetSlots: ["hello@qihang.ai", "48 小时内回复", "英国工作时间"],
    tone: "pearl",
  },
  {
    id: "product",
    eyebrow: "Product Conversation",
    title: "适合讨论的问题，应该先被说清楚。",
    summary: "联系页的第二段不再做并列卡片，而是明确告诉访客哪些方向最值得来信。",
    details: [
      { label: "原型讨论", body: "适合讨论形态、模式切换、使用场景和设备节奏。" },
      { label: "工作流反馈", body: "适合交流数据、训练、评测和模型发布路径。" },
      { label: "合作探索", body: "适合讨论真实部署与产品落地方向。" },
    ],
    stageLabel: "适合来信的话题",
    stageSummary: "把沟通方向说清，反而比堆更多联系方式更有效。",
    stageTags: ["原型", "工作流", "合作"],
    assetSlots: ["原型照片", "工作流录屏", "合作说明"],
    tone: "midnight",
  },
  {
    id: "privacy",
    eyebrow: "Sensitive Topics",
    title: "安全和隐私问题需要更直接的入口。",
    summary: "涉及隐私边界、数据安全和合规话题时，用户不应该再去翻找复杂的联系路径。",
    details: [
      { label: "安全问题", body: "直接在标题中标注 Security，方便更快进入处理流程。" },
      { label: "隐私反馈", body: "围绕采集边界、默认值和状态可见的意见也应优先处理。" },
      { label: "系统边界", body: "涉及平台信任边界的问题，应能快速进入一条明确通道。" },
    ],
    stageLabel: "敏感议题通道",
    stageSummary: "最后一段强调敏感议题通道，而不是让联系方式页停留在泛泛而谈。",
    stageTags: ["Security", "Privacy", "Trust"],
    assetSlots: ["隐私边界图", "安全说明", "响应流程"],
    tone: "obsidian",
  },
];

export const UPDATES_STORY_SCENES: StorySceneContent[] = [
  {
    id: "march-structure",
    eyebrow: "2026.03",
    title: "公开站展示重排",
    summary: "首页和产品页进一步拉开主视觉与段落节奏，让产品舞台优先于解释性卡片出现。",
    details: [
      { label: "主视觉", body: "首屏先看产品，而不是先被流程说明包围。" },
      { label: "节奏", body: "页面从 section 叠加改成连续分镜。" },
      { label: "语言", body: "内部设计语言被替换成面向用户感知的表达。" },
    ],
    stageLabel: "公开站展示重排",
    stageSummary: "这次更新的重点不是换配色，而是把首页和产品页改成真正的叙事结构。",
    stageTags: ["Homepage", "Product", "Narrative"],
    assetSlots: ["新版首页录屏", "产品页录屏", "旧新版对比"],
    tone: "pearl",
  },
  {
    id: "march-demo",
    eyebrow: "2026.03",
    title: "Demo 主流程优先",
    summary: "公开体验页优先暴露设备舞台、运行入口和结果摘要，把工程控制收进更克制的交互层。",
    details: [
      { label: "主舞台", body: "Demo 首先服务于产品感知，而不是参数暴露。" },
      { label: "结果摘要", body: "关键结果先看懂，再决定是否展开控制项。" },
      { label: "控制抽屉", body: "更重的工程动作被折叠，减少首次体验噪音。" },
    ],
    stageLabel: "Demo 主流程优先",
    stageSummary: "体验页更像一个交互实验室，而不是一张工程参数面板。",
    stageTags: ["Demo", "Lab", "Result"],
    assetSlots: ["Demo 主舞台", "结果摘要", "控制抽屉"],
    tone: "midnight",
  },
  {
    id: "march-security",
    eyebrow: "2026.03",
    title: "安全默认值加固",
    summary: "继续强化 CSRF、限流、签名读取和生产配置校验，让工作台默认处于更可信的边界内。",
    details: [
      { label: "签名读取", body: "前端继续保持受管访问，不暴露原始对象路径。" },
      { label: "请求边界", body: "Cookie、workspace 与 CSRF 共同参与敏感请求校验。" },
      { label: "生产配置", body: "继续收紧生产环境默认值，减少误配置风险。" },
    ],
    stageLabel: "安全默认值加固",
    stageSummary: "更新页最后一段只记录真正影响信任边界的变化。",
    stageTags: ["CSRF", "Rate Limit", "Signed Access"],
    assetSlots: ["安全拓扑", "配置校验", "访问路径"],
    tone: "obsidian",
  },
];

export const WORKFLOW_RAIL: RailItem[] = [
  { label: "01", title: "体验", body: "从 Demo 理解对象、输入和反馈。", meta: "Demo" },
  { label: "02", title: "整理", body: "上传样本，冻结版本，保持边界清楚。", meta: "Datasets" },
  { label: "03", title: "训练", body: "查看日志、指标和产物。", meta: "Train" },
  { label: "04", title: "发布", body: "登记模型版本并切换 alias。", meta: "Release" },
];

export const PRICING_COMPARE_RAIL: RailItem[] = [
  { label: "Explore", title: "公开体验层", body: "公开 Demo、基础推理、无控制台协作。", meta: "Free" },
  { label: "Studio", title: "完整工作流", body: "项目、数据集、训练、模型仓、发布回滚。", meta: "Waitlist" },
  { label: "Team", title: "协作与额度", body: "多人 workspace、更高并发、细粒度权限。", meta: "Soon" },
];

export const DOCS_PATH_RAIL: RailItem[] = [
  { label: "Product", title: "产品说明", body: "先理解硬件、模式和 Demo 定位。" },
  { label: "Workflow", title: "工作流入口", body: "再理解数据、训练、评测与发布关系。" },
  { label: "Security", title: "部署与安全", body: "最后查看私有存储、签名访问和默认值。" },
];

export const UPDATE_TIMELINE_RAIL: RailItem[] = [
  { label: "2026.03", title: "公开站展示重排", body: "主视觉与段落节奏重新拉开。" },
  { label: "2026.03", title: "Demo 主流程优先", body: "首屏优先设备舞台和结果摘要。" },
  { label: "2026.03", title: "安全默认值加固", body: "继续强化 CSRF、限流和签名读取。" },
];
